### ISSUE TITLE
GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by Ordinaryperson2** [neuratech-ai/ComfyUI-MultiGPU#9]
When running the model (Flux dev fp8) on cuda:0 (RTX 4070 Ti Super) and the VAE on cuda:1 (GTX 1070) VAE Decode fails with this error. Swapping the devices works but is obviously not fast, running both on the 1070 works too.
I can imagine it's some kind of architectural/CUDA compat issue, but idk how to fix this and perhaps the nodes could account for it if possible?

# ComfyUI Error Report
## Error Details
- **Node Type:** VAEDecode
- **Exception Type:** RuntimeError
- **Exception Message:** GET was unable to find an engine to execute this computation
## Stack Trace
```
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 284, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 328, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\autoencoder.py", line 137, in decode
    x = self.decoder(z, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 625, in forward
    h = self.conv_in(z)
        ^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_tensor.py", line 1437, in __torch_function__
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 2252812152
  - **Torch VRAM Total:** 13186891776
  - **Torch VRAM Free:** 146489208

## Logs
```
2024-10-08 17:48:03,313 - root - INFO - Total VRAM 16376 MB, total RAM 31832 MB
2024-10-08 17:48:03,313 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-08 17:48:03,314 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-08 17:48:03,314 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-10-08 17:48:04,244 - root - INFO - Using pytorch cross attention
2024-10-08 17:48:05,588 - root - INFO - [Prompt Server] web root: C:\ComfyUI_windows_portable\ComfyUI\web
2024-10-08 17:48:06,268 - root - INFO - Total VRAM 16376 MB, total RAM 31832 MB
2024-10-08 17:48:06,268 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-08 17:48:06,268 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-08 17:48:06,268 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-10-08 17:48:07,862 - root - INFO - 
Import times for custom nodes:
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyBootlegOffloadCPU.py
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MultiGPU-main
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Merlin
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-08 17:48:07,862 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4-master
2024-10-08 17:48:07,863 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\img2txt-comfyui-nodes
2024-10-08 17:48:07,863 - root - INFO -    1.5 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-08 17:48:07,863 - root - INFO - 
2024-10-08 17:48:07,866 - root - INFO - Starting server

2024-10-08 17:48:07,866 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-08 17:48:54,723 - root - INFO - got prompt
2024-10-08 17:48:54,762 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:48:54,764 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:48:55,425 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-10-08 17:48:55,430 - root - INFO - model_type FLUX
2024-10-08 17:49:08,572 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:49:08,573 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:49:09,240 - root - INFO - Requested to load FluxClipModel_
2024-10-08 17:49:09,240 - root - INFO - Loading 1 new model
2024-10-08 17:49:09,247 - root - INFO - loaded completely 0.0 4777.53759765625 True
2024-10-08 17:49:22,490 - root - INFO - Requested to load FluxClipModel_
2024-10-08 17:49:22,490 - root - INFO - Loading 1 new model
2024-10-08 17:49:22,494 - root - INFO - loaded completely 0.0 323.94775390625 True
2024-10-08 17:49:26,614 - root - INFO - Requested to load FluxClipModel_
2024-10-08 17:49:26,614 - root - INFO - Loading 1 new model
2024-10-08 17:49:31,017 - root - INFO - Requested to load Flux
2024-10-08 17:49:31,017 - root - INFO - Loading 1 new model
2024-10-08 17:49:37,891 - root - INFO - loaded completely 0.0 11350.048889160156 True
2024-10-08 17:49:48,120 - root - INFO - Requested to load AutoencodingEngine
2024-10-08 17:49:48,121 - root - INFO - Loading 1 new model
2024-10-08 17:49:48,419 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-10-08 17:49:48,675 - root - ERROR - !!! Exception during processing !!! GET was unable to find an engine to execute this computation
2024-10-08 17:49:48,770 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 284, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 328, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\autoencoder.py", line 137, in decode
    x = self.decoder(z, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 625, in forward
    h = self.conv_in(z)
        ^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_tensor.py", line 1437, in __torch_function__
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: GET was unable to find an engine to execute this computation

2024-10-08 17:49:48,773 - root - INFO - Prompt executed in 54.05 seconds
2024-10-08 17:51:42,719 - root - INFO - got prompt
2024-10-08 17:51:46,533 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:51:46,534 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:51:47,705 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
2024-10-08 17:51:47,707 - root - INFO - model_type FLUX
2024-10-08 17:52:00,480 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:52:00,481 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:52:10,402 - root - INFO - Requested to load Flux
2024-10-08 17:52:10,403 - root - INFO - Loading 1 new model
2024-10-08 17:52:14,084 - root - INFO - loaded partially 5757.674912261963 5756.669006347656 0
2024-10-08 17:55:25,120 - root - INFO - Requested to load AutoencodingEngine
2024-10-08 17:55:25,121 - root - INFO - Loading 1 new model
2024-10-08 17:55:25,407 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-10-08 17:55:26,539 - root - INFO - Prompt executed in 223.82 seconds
2024-10-08 17:55:49,204 - root - INFO - got prompt
2024-10-08 17:55:51,687 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:55:51,688 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:55:53,061 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-10-08 17:55:53,063 - root - INFO - model_type FLUX
2024-10-08 17:56:06,086 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:56:06,086 - root - INFO - Using pytorch attention in VAE
2024-10-08 17:56:06,710 - root - INFO - Requested to load FluxClipModel_
2024-10-08 17:56:06,710 - root - INFO - Loading 1 new model
2024-10-08 17:56:06,716 - root - INFO - loaded completely 0.0 4777.53759765625 True
2024-10-08 17:56:18,488 - root - INFO - Requested to load FluxClipModel_
2024-10-08 17:56:18,488 - root - INFO - Loading 1 new model
2024-10-08 17:56:18,558 - root - INFO - loaded completely 0.0 2237.80810546875 True
2024-10-08 17:56:22,005 - root - INFO - Requested to load Flux
2024-10-08 17:56:22,005 - root - INFO - Loading 1 new model
2024-10-08 17:56:29,052 - root - INFO - loaded completely 0.0 11350.048889160156 True
2024-10-08 17:56:39,140 - root - INFO - Requested to load AutoencodingEngine
2024-10-08 17:56:39,140 - root - INFO - Loading 1 new model
2024-10-08 17:56:39,378 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-10-08 17:56:39,920 - root - ERROR - !!! Exception during processing !!! GET was unable to find an engine to execute this computation
2024-10-08 17:56:39,932 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 284, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 328, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\autoencoder.py", line 137, in decode
    x = self.decoder(z, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 625, in forward
    h = self.conv_in(z)
        ^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_tensor.py", line 1437, in __torch_function__
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: GET was unable to find an engine to execute this computation

2024-10-08 17:56:39,940 - root - INFO - Prompt executed in 50.73 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":25,"last_link_id":38,"nodes":[{"id":8,"type":"VAEDecode","pos":{"0":1209,"1":188},"size":{"0":210,"1":46},"flags":{},"order":8,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":38}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"}},{"id":12,"type":"DualCLIPLoaderGGUF","pos":{"0":-286,"1":326},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[20],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DualCLIPLoaderGGUF"},"widgets_values":["t5-v1_1-xxl-encoder-Q3_K_S.gguf","clip_l.safetensors","flux"]},{"id":9,"type":"SaveImage","pos":{"0":1440,"1":187},"size":{"0":597.11669921875,"1":642.2105712890625},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":7,"type":"CLIPTextEncode","pos":{"0":413,"1":389},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":22}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""]},{"id":6,"type":"CLIPTextEncode","pos":{"0":415,"1":186},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":21}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["The Arcane Tower looms before you, an ancient stone structure wrapped in twisting vines. Its windows emit an ethereal glow, hinting at the arcane rituals performed within."]},{"id":5,"type":"EmptyLatentImage","pos":{"0":473,"1":609},"size":{"0":315,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[384,384,1]},{"id":3,"type":"KSampler","pos":{"0":863,"1":186},"size":{"0":315,"1":262},"flags":{},"order":7,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":37},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[159189119108119,"fixed",22,1.5,"euler","normal",1]},{"id":25,"type":"CheckpointLoaderMultiGPU","pos":{"0":-311,"1":156},"size":{"0":340.20001220703125,"1":122},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[37],"shape":3,"slot_index":0},{"name":"CLIP","type":"CLIP","links":null,"shape":3},{"name":"VAE","type":"VAE","links":null,"shape":3}],"properties":{"Node name for S&R":"CheckpointLoaderMultiGPU"},"widgets_values":["flux1-dev-fp8.safetensors","cuda:0"]},{"id":14,"type":"OverrideCLIPDevice","pos":{"0":54,"1":326},"size":{"0":315,"1":58},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":20}],"outputs":[{"name":"CLIP","type":"CLIP","links":[21,22],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"OverrideCLIPDevice"},"widgets_values":["cuda:1"]},{"id":24,"type":"VAELoaderMultiGPU","pos":{"0":-283,"1":475},"size":{"0":315,"1":82},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[38],"shape":3,"slot_index":0}],"properties":{"Node name for S&R":"VAELoaderMultiGPU"},"widgets_values":["ae.safetensors","cuda:1"]}],"links":[[2,5,0,3,3,"LATENT"],[4,6,0,3,1,"CONDITIONING"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[9,8,0,9,0,"IMAGE"],[20,12,0,14,0,"CLIP"],[21,14,0,6,0,"CLIP"],[22,14,0,7,0,"CLIP"],[37,25,0,3,0,"MODEL"],[38,24,0,8,1,"VAE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[553.0049673539946,436.97666326287884]}},"version":0.4}
```

**Comment by nuaimat** [comment]
+1 same here for "Split FLUX.1-dev across two GPUs" example in this repo workflow link: https://github.com/neuratech-ai/ComfyUI-MultiGPU/blob/main/examples/flux1dev_2gpu.json

**Comment by MadPonyInteractive** [comment]
I had the same issue running any and all examples.
